### ISSUE TITLE
translations.sql

### ISSUE THREAD

**Issue by deman4ik** [Leerion/discoElysiumExplorer#1]
Искал тексты диалогов и наткнулся на твой проект. Очень круто. Можешь пожалуйста выложить таблицу с переводами?

**Comment by Leerion** [comment]
> Очень круто. 
Спасибо!

Вся база (кроме озвучки) хранится в папке migrations. Если правильно помню, в файле [disco_dialogues.sql] - сами диалоги (фразы по отдельности), в папки [disco_links.sql] - их взаимосвязи, в файле [disco_conversations.sql] - общая информация о диалогах, как совокопности фраз. Ну и в файле [disco_actors.sql] - информация о персонажах.

Если интересует инфа, как это всё связывается, могу логику отдельно расписать.

**Comment by Leerion** [comment]
> Очень круто.

Спасибо!

Если интересует русский перевод, есть в csv формате. Я его относительно давно делал, там в игру могли что-нибудь добавить по диалогам, но в целом он актуальный.

[translations.csv](https://github.com/Leerion/discoElysiumExplorer/files/10322347/translations.csv)
